env:
  browser: true
  es2021: true
  react-native/react-native: true
extends:
  - '@react-native-community'
  - plugin:react/recommended
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
  - prettier
  - 'prettier/@typescript/eslint'
  - prettier/react
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-native
  - '@typescript-eslint'
rules: {}
